.\" Man Page for bioctl
.TH BIOCTL 1 "August 05, 2018"
.SH "NAME"
bioctl \- control tool for biometric authentication
.SH "SYNOPSIS"
.B bioctl
.SH "DESCRIPTION"
.B bioctl
is a control tool for biometric authentication in the UKUI desktop.
It show or change the status that biometric authentication is enabled or not.
.TP
\fB status\fR
Show the status of biometric authentication.
.TP
\fB enable\fR
Enable biometric authentication.
.TP
\fB disable\fR
Disable biometric authenticaion.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui/ukui-biometric-auth/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
yanghao <yanghao@kylinos.cn> (2018)
