.\" Man Page for biometric-manager
.TH BIOMETRIC-MANAGER 1 "August 13, 2018"
.SH "NAME"
biometric-manager \- management tool for biometric authentication
.SH "SYNOPSIS"
.B biometric-manager
.SH "DESCRIPTION"
.B biometric-manager
is a tool for managing biometric authentication.
It can control the opening or closing of biometric authentication.
It also control the opening or closing of biometric devices' drivers.
You can use it to enroll or delete biometric features.
You can only see your own features in a session unless you are root.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui/ukui-biometric-manager/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
yanghao <yanghao@kylinos.cn> (2018)
