.\" Man Page for ukui-pam-biometric-gui
.TH UKUI-PAM-BIOMETRIC-GUI 1 "August 05, 2018"
.SH "NAME"
ukui-pam-biometric-gui \- Prompt Dialog for biometric authentication
.SH "SYNOPSIS"
.B ukui-pam-biometric-gui
.SH "DESCRIPTION"
.B ukui-pam-biometric-gui
is a prompt dialog for biometric authentication in the UKUI desktop.
It is called by pam_biometric module and show prompt for user when the user
uses biometric authentication to authenticate su or sudo.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui/ukui-pam-biometric-gui/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
yanghao <yanghao@kylinos.cn> (2018)
