#!/bin/bash

# Usage: bioctl status|enable|disable

if [ "$1" = "enable" ]; then
	pkexec /usr/bin/bioctl-helper enable
elif [ "$1" = "disable" ]; then
	pkexec /usr/bin/bioctl-helper disable
elif [ "$1" = "status" ]; then
	/usr/bin/bioctl-helper status
else
	echo "Usage: bioctl status|enable|disable"
fi

exit 0
